data:
  train_files: None  # Will be overridden in training script
  val_files: None   # Will be overridden in training script
  prompt_key: problem
  max_prompt_length: 1300
  max_response_length: 2000
  rollout_batch_size: 8  # Reduced for 4 GPUs
  shuffle: true
  seed: 42
  max_pixels: 12845056
  min_pixels: 3136

algorithm:
  adv_estimator: grpo
  kl_coef: 0.0

worker:
  actor:
    global_batch_size: 16  # Keep same total batch size
    micro_batch_size_per_device_for_update: 8  # Reduced per device
    micro_batch_size_per_device_for_experience: 8  # Reduced per device
    max_grad_norm: 1.0
    use_kl_loss: true
    kl_loss_coef: 5.0e-3
    kl_loss_type: low_var_kl
    model:
      model_path: Qwen/Qwen2.5-VL-7B-Instruct
      enable_gradient_checkpointing: true
    optim:
      lr: 1.0e-6
      weight_decay: 1.0e-2
    fsdp:
      param_offload: false
      optimizer_offload: false
      torch_dtype: null
    offload:
      param_offload: true
      optimizer_offload: true

  rollout:
    temperature: 1.0
    tensor_parallel_size: 2  # Use 2 GPUs for model parallelism
    gpu_memory_utilization: 0.7  # Higher utilization for A100 80G
    n: 4  # Reduced for 4 GPUs
    enable_chunked_prefill: true

  ref:
    offload:
      param_offload: true

  reward:
    reward_type: function
    compute_score: brain_tumor_3d

trainer:
  total_episodes: 15  # Increased for proper RL training
  logger: ["console", "wandb"]
  project_name: brain_tumor_3d_4x80G
  n_gpus_per_node: 4  # 4 GPUs per node
  nnodes: 1
  save_freq: 100
  test_freq: 2  # Validate every 2 episodes
  val_before_train: true  # Validate before training starts
  val_only: false