data:
  train_files: None  # Will be overridden in training script
  val_files: None   # Will be overridden in training script
  prompt_key: problem
  max_prompt_length: 28000  # Increased to accommodate video tokens (155 frames × ~130 tokens/frame ≈ 20k + text)
  max_response_length: 2000
  rollout_batch_size: 8  # Reduced for 4 GPUs
  shuffle: true
  seed: 42
  max_pixels: 12845056
  min_pixels: 3136

algorithm:
  adv_estimator: grpo
  kl_coef: 0.0

worker:
  actor:
    global_batch_size: 8  # (8 * rollout.n=8) / 4 GPUs = 16 per device
    micro_batch_size_per_device_for_update: 2  # Reduced to 2 to save GPU memory (16 / 2 = 8 accumulation steps)
    micro_batch_size_per_device_for_experience: 4
    max_grad_norm: 1.0
    use_kl_loss: true
    kl_loss_coef: 5.0e-3
    kl_loss_type: low_var_kl
    model:
      model_path: Qwen/Qwen2.5-VL-7B-Instruct
      enable_gradient_checkpointing: true
    optim:
      lr: 1.0e-6
      weight_decay: 1.0e-2
    fsdp:
      param_offload: false
      optimizer_offload: false
      torch_dtype: null
    offload:
      param_offload: true
      optimizer_offload: true

  rollout:
    temperature: 1.0
    tensor_parallel_size: 1  # Single GPU inference (7B model fits easily)
    gpu_memory_utilization: 0.6  # Conservative for single GPU
    n: 8  # Increased samples for GRPO (4 GPUs can handle more)
    enable_chunked_prefill: true
    max_num_batched_tokens: 32768  # Increased to handle video multi-modal embeddings

  ref:
    offload:
      param_offload: true

  reward:
    reward_type: function
    compute_score: brain_tumor_3d

trainer:
  total_episodes: 15  # Increased for proper RL training
  logger: ["console"]  # Disabled wandb for debugging
  project_name: brain_tumor_3d_4x80G
  n_gpus_per_node: 4  # 4 GPUs per node
  nnodes: 1
  save_freq: 100
  test_freq: 458  # Validate every 2 episodes (approx. 229 steps/episode × 2)
  val_before_train: true  # Validate before training starts
  val_only: false