data:
  train_files: None  # Will be overridden in training script
  val_files: None   # Will be overridden in training script
  prompt_key: problem
  max_prompt_length: 28000  # Increased to accommodate video tokens (155 frames × ~130 tokens/frame ≈ 20k + text)
  max_response_length: 512  # Reduced from 2000 to prevent OOM from long JSON responses
  rollout_batch_size: 8  # Reduced for 4 GPUs
  shuffle: true
  seed: 42
  max_pixels: 12845056
  min_pixels: 3136

algorithm:
  adv_estimator: grpo
  kl_coef: 0.0

worker:
  actor:
    global_batch_size: 8  # Reduced from 16 to 8 for memory safety
    micro_batch_size_per_device_for_update: 1  # Reduced to 1 to avoid OOM in backward pass
    micro_batch_size_per_device_for_experience: 1  # Reduced to 1 to match update batch size
    max_grad_norm: 1.0
    use_kl_loss: true
    kl_loss_coef: 5.0e-3
    kl_loss_type: low_var_kl
    model:
      model_path: Qwen/Qwen2.5-VL-7B-Instruct
      enable_gradient_checkpointing: true
    optim:
      lr: 1.0e-6
      weight_decay: 1.0e-2
      lr_warmup_steps_ratio: 0.0  # No warmup
      training_steps: 3435  # 229 batches × 15 episodes
    fsdp:
      param_offload: false
      optimizer_offload: false
      torch_dtype: null
    offload:
      param_offload: true
      optimizer_offload: true

  rollout:
    temperature: 1.0
    tensor_parallel_size: 1  # Single GPU inference (7B model fits easily)
    gpu_memory_utilization: 0.55  # Further reduced from 0.6 to leave more room for FSDP
    n: 4  # Increased from 2 to 4 for better GRPO sample diversity (rollout is inference-only, minimal memory impact)
    enable_chunked_prefill: true
    max_num_batched_tokens: 32768  # Increased to handle video multi-modal embeddings

  ref:
    offload:
      param_offload: true

  reward:
    reward_type: function
    compute_score: brain_tumor_3d

trainer:
  total_episodes: 15  # Increased for proper RL training
  logger: ["console"]  # Disabled wandb for debugging
  project_name: brain_tumor_3d_4x80G
  n_gpus_per_node: 4  # 4 GPUs per node
  nnodes: 1
  save_freq: 100
  test_freq: 458  # Validate every 2 episodes (approx. 229 steps/episode × 2)
  val_before_train: true  # Validate before training starts
  val_only: false